-- 1번

SELECT S.JOB_ID, MAX(SALARY), MIN(SALARY)
FROM (
SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE 'SA%') S
GROUP BY JOB_ID;

-- 2번
SELECT JOB_ID, MAX(SALARY) AS MAX_SAL
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY MAX_SAL DESC;

-- 3번

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE EMPLOYEES.SALARY BETWEEN (SELECT MIN(SALARY)
FROM EMPLOYEES E, (SELECT JOB_ID
FROM JOBS
WHERE JOB_TITLE LIKE '%Programmer%') J
WHERE E.JOB_ID=J.JOB_ID) AND (SELECT MAX(SALARY)
FROM EMPLOYEES E, (SELECT JOB_ID
FROM JOBS
WHERE JOB_TITLE LIKE '%Programmer%') J
WHERE E.JOB_ID=J.JOB_ID);

-- 4번
SELECT FIRST_NAME AS '이름', LAST_NAME AS '성', SALARY AS '연봉'
FROM EMPLOYEES
WHERE JOB_ID=(SELECT JOB_ID
FROM JOBS
WHERE JOB_TITLE='Sales Representative')
AND SALARY BETWEEN 9000 AND 10000
ORDER BY FIRST_NAME;

-- 5번
SELECT E.EMPLOYEE_ID AS '사번', E.FIRST_NAME AS '이름', J.JOB_TITLE AS '업무명', D.DEPARTMENT_NAME AS '부서명'
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND E.JOB_ID=J.JOB_ID
AND D.LOCATION_ID=(SELECT DISTINCT D.LOCATION_ID
FROM DEPARTMENTS D, LOCATIONS L
WHERE D.LOCATION_ID=L.LOCATION_ID
AND CITY='Seattle');

-- 6번
SELECT J.JOB_TITLE AS '업무명', SUM(E.SALARY) AS '연봉'
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID=J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING SUM(E.SALARY)>30000
ORDER BY SUM(E.SALARY) DESC;

-- 7번
SELECT E1.LAST_NAME, E1.SALARY
FROM EMPLOYEES E1, EMPLOYEES E2
WHERE E1.MANAGER_ID=E2.EMPLOYEE_ID
AND E1.SALARY>E2.SALARY;

-- 8번
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, D.DEPARTMENT_NAME, 매니저명
FROM (SELECT E1.EMPLOYEE_ID, E1.FIRST_NAME, E1.DEPARTMENT_ID, E2.FIRST_NAME '매니저명'
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.MANAGER_ID=E2.EMPLOYEE_ID) AS EMP LEFT JOIN DEPARTMENTS D
ON EMP.DEPARTMENT_ID=D.DEPARTMENT_ID;

-- 9번
SELECT E1.EMPLOYEE_ID, 

